version: '3'
      
volumes:
  redis:
  db:

services:

  db:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    command:
      - "--character-set-server=utf8"
      - "--innodb_log_buffer_size=32M"
      - "--innodb_log_file_size=80M"
      - "--max_allowed_packet=8M"
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql'

  redis:
    image: 'redis:4.0-alpine'
    hostname: redis
    container_name: redis
    command: 'redis-server --requirepass root123'
    sysctls:
      net.core.somaxconn: 1024
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    depends_on:
      - 'db'
      - 'redis'
    image: 'test-account:latest'
    container_name: test-account
    hostname: test-account
    restart: always
    command: /bin/bash -c "bundle exec rails db:create db:migrate && bundle exec puma -C config/puma.rb"
    volumes:
      - '.:/app'
    ports:
      - "3000:3000"
    env_file:
      - '.env'
    stdin_open: true
    tty: true

  sidekiq:
    depends_on:
      - 'web'
    image: 'test-account:latest'
    container_name: sidekiq
    command: 'bundle exec sidekiq -C config/sidekiq.yml.erb'
    volumes:
      - '.:/app'
    env_file:
      - '.env'